package com.yuecheng.workportal.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yuecheng.workportal.bean.LoginUser;
import com.yuecheng.workportal.module.conversation.bean.Conversation;

import com.yuecheng.workportal.greendao.LoginUserDao;
import com.yuecheng.workportal.greendao.ConversationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginUserDaoConfig;
    private final DaoConfig conversationDaoConfig;

    private final LoginUserDao loginUserDao;
    private final ConversationDao conversationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginUserDaoConfig = daoConfigMap.get(LoginUserDao.class).clone();
        loginUserDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        loginUserDao = new LoginUserDao(loginUserDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);

        registerDao(LoginUser.class, loginUserDao);
        registerDao(Conversation.class, conversationDao);
    }
    
    public void clear() {
        loginUserDaoConfig.clearIdentityScope();
        conversationDaoConfig.clearIdentityScope();
    }

    public LoginUserDao getLoginUserDao() {
        return loginUserDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

}
